name: Scrape Election Data

on:
  schedule:
    - cron: '*/10 * * * *' # 매 10분마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Python 3.x 사용 (예: 3.9, 3.10)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add voting_progress.json
        git commit -m "Update voting_progress.json with latest data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
