name: Scrape Election Data

on:
  schedule:
    - cron: '*/30 * * * *'  # 매 30분마다 실행
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push JSON files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        if [ -n "$(git status --porcelain election_data.json election_summary.json)" ]; then
          git add election_data.json election_summary.json
          git commit -m "Update election data and summary $(date)"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
