name: Scrape Election Data

on:
  schedule:
    - cron: '*/10 * * * *'  # 매 10분마다 실행
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push JSON file
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        # 커밋 시간을 UTC로 명시적으로 설정
        export GIT_COMMITTER_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        export GIT_AUTHOR_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        if [ -n "$(git status --porcelain voting_progress.json)" ]; then
          git add voting_progress.json
          git commit -m "Update voting progress data $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
